title: Ornella VACCARELLI - Sr. Research Scientist

# Theme primary chooses
cello: &cello "#434E5E"
curious_blue: &curious_blue "#3582C4"
eucalyptus: &eucalyptus "#22A162"
scooter: &scooter "#328998"
governor_bay: &governor_bay "#59578E"
cosmic: &cosmic "#80425F"

theme_color: *cosmic
description: Ornella VACCARELLI - Sr. Research Scientist
repository: ovaccarelli/cvornellavaccarelli

sass:
  style: compact
